// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../src/IssuerVerifier.sol";
import "../src/BBSVerifier.sol";

contract InteractScript is Script {
    function run() external {
        // Load the deployed IssuerVerifier contract
        IssuerVerifier issuerVerifier = IssuerVerifier(0x1C8d253077Ffc69C5161a68C3c52d86b78Db3F3B);        
        vm.startBroadcast();

    // 1. Test stashNullifier
    // Read user address from environment.
    // Set USER_ADDRESS in your shell before running the script.
    address user = vm.envAddress("USER_ADDRESS");
    require(user != address(0), "USER_ADDRESS not set in env");
    console.log("Using user address from env:");
    console.logAddress(user);
    uint256 m_null = 192837465;
        bytes32 N = keccak256(abi.encodePacked(user, m_null));
        
        console.log("Stashing Nullifier...");
        issuerVerifier.stashNullifier(N);
        console.log("Stash Success! Nullifier exists:", issuerVerifier.keyExist(N));

        // 2. Test verifyAndMint
        // Currently use a valid proof generated by the test_rng in wasm. 
        BBSVerifier.Proof memory proof = BBSVerifier.Proof({
            A_bar: BBSMath.G1Point(18240449537066144224374956612927054362722724221656931348090417631743859197384, 9219297243724659693974501719167475285107135868283376375754495406007940627103),
            B_bar: BBSMath.G1Point(3722135581318468566903890117346542015830640382754361500474997601945512614300, 3524037676911001584192983393295475122659736155527353835007614541310400852872),
            U: BBSMath.G1Point(17942713163671002772048476628456036555361061105266416839098197374779677304219, 6358543843323181799283503706896002459221761971952669513594424446307322210490),
            s: 19520145271776029937683947518516203872450041095466355072915075574615239343812,
            t: 12403803877892551323243645288320623263978788684600641656202520356751162864536,
            u_gamma: 2770982020189074713186096940998458865333388660612628666011804758211952355741
        });

        uint256[] memory constraints = new uint256[](4);
        constraints[0] = uint256(0x6acbcbbc11c81227f015cba2082d6b71a8792fee9e139685dec3cc78556ba724);
        constraints[1] = uint256(0x43209a421195688f1d02b91a0f147396c9d214f488a3c501ad3f73fd10c3da1f);
        constraints[2] = uint256(0x6fdf09da2cebbbdbd7e38e0efd01288065743c2a87b82fadd86a1af98ffc3184);
        constraints[3] = uint256(0xc4ce3210982aa6fc94dabe46dc1dbf454d54a3a2fbc51d2ae982e47c784f4608);

        // Test our valid proof.
        issuerVerifier.verifyAndMint(proof, m_null, constraints, user);

        vm.stopBroadcast();
    }
}