// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../src/IssuerVerifier.sol";
import "../src/BBSVerifier.sol";

contract InteractScript is Script {
    function run() external {
        // Load the deployed IssuerVerifier contract
        IssuerVerifier issuerVerifier = IssuerVerifier(0x784891b3a09e03086bD6F91af752eb6bF67023d9);        
        vm.startBroadcast();

        // 1. Test stashNullifier
        // Read user address from environment.
        // Set USER_ADDRESS in your shell before running the script.
        address user = vm.envAddress("USER_ADDRESS");
        require(user != address(0), "USER_ADDRESS not set in env");
        console.log("Using user address from env:");
        console.logAddress(user);
        uint256 m_null = 192837465;
        bytes32 N = keccak256(abi.encodePacked(user, m_null));
        
        console.log("Stashing Nullifier...");
        issuerVerifier.stashNullifier(N);
        console.log("Stash Success! Nullifier exists:", issuerVerifier.keyExist(N));

        // 2. Test verifyAndMint
        // Currently use a valid proof generated by the test_rng in wasm. 
        BBSVerifier.Proof memory proof = BBSVerifier.Proof({
            A_bar: BBSMath.G1Point(4179854549373647938910268115294581072706185687863174413170531162448041131203, 20210025142984011222056652656858926876353227415128028875057893584335833094561),
            B_bar: BBSMath.G1Point(1227402969657634430354195601747756016090133927089280083753025295027110736534, 8458497876411656801318655241350188994967206519721285737959024229403265170867),
            U: BBSMath.G1Point(17035810371453626241387371415567993318867865234729471761922831284708394104835, 99219156246168972039876991172570883884327041166160191052837059427977499355),
            s: 16018637230591439904573643880561864201630462128299484899669309922016419721602,
            t: 10582240665604962484703294327720900488520972873170677218820877890427331109089,
            u_gamma: 10372339021769194516104634340022921528470216438246179471902157948573761865541
        });

        uint256[] memory expectedConstraints = new uint256[](4);
        expectedConstraints[0] = 4528752285148684012564256818462280771918828852546138746521208354411044252822;// keccak(Age=18) % FR_Modular
        expectedConstraints[1] = 8474321739458138899097646849860765932135651313862925479195387843221486033438;// Nationality=US
        expectedConstraints[2] = 1464662865008959075347130388737553683672515905673906344791000457739484483820;// Verified=true
        expectedConstraints[3] = 1464662865008959075347130388737553683672515905673906344791000457739484483820;// Empty

        // Test our valid proof.
        issuerVerifier.verifyAndMint(proof, m_null, expectedConstraints, user);

        vm.stopBroadcast();
    }
}