// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../src/BBSMath.sol";
import "../src/BBSVerifier.sol";
import "../src/IssuerVerifier.sol";

contract DeployIssuerVerifier is Script {
    function run() external {
        // Local env derive
        // You should set your PRIVATE_KEY in the shell environment
        vm.startBroadcast();

        // Set the params for BBSVerifier
        // Currently using params that generated by the test_rng in wasm
        BBSMath.G2Point memory pk = BBSMath.G2Point({
            x: [uint256(3260306681974474822604563648776815682816091416970286175188033719997424721292), 21078157932976788369811386224298604876283678095953300695193627580536184663017], 
            y: [uint256(15974835493233460998260511752626128505010865937675816409903067489306439600529), 21872932232854780648641376857253831029627783545362812619304934661720191529610]
        }); // sk = // 1328790040692576325258580129229001772890358018148159309458854770206210226319
        
        BBSMath.G1Point[] memory bases = new BBSMath.G1Point[](6);
        bases[0] = BBSMath.G1Point({x: 1240703902419481545648986623473745806820787811594483762868555478458184666010, y: 18256809644617940920254137422873442228473372063501986223346572230462785524439});
        bases[1] = BBSMath.G1Point({x: 13020051060923754131228834502880722230806022247808159414293488215070332394772, y: 4529195280833079968741232889459250032235684423945803123503195484318934791269});
        bases[2] = BBSMath.G1Point({x: 16297305326858617051978407466566022015897499588105011865519416711980789611480, y: 3457763090096090198366700259693644531770479248862060079356697617968728920669});
        bases[3] = BBSMath.G1Point({x: 2253800715866524994843494300154676387161899760404330152495442103191129641090, y: 9799921154527725974487574934896288658143635125210110869057393462183450014056});
        bases[4] = BBSMath.G1Point({x: 15591676955350207499762345130216057388364340524562767442403038585836757427173, y: 366693626097570863962860699973119751999356879228643136313636147692477681999});
        bases[5] = BBSMath.G1Point({x: 21393812497764701958592826102470503271515498520329721604743009071119726253411, y: 16563212233814295780128168415970014578295470256244992910750946401593357383812});

        // 2. Deploy the BBSVerifier
        BBSVerifier bbsVerifier = new BBSVerifier(pk, bases);
        
        // 3. Set up the expected constraints for the IssuerVerifier
        // In a real application, could use `cast keccak <constraint_name>=<value>` to gen these values.
        uint256[] memory expectedConstraints = new uint256[](4);
        expectedConstraints[0] = 4528752285148684012564256818462280771918828852546138746521208354411044252822;// keccak(Age=18) % FR_Modular
        expectedConstraints[1] = 8474321739458138899097646849860765932135651313862925479195387843221486033438;// Nationality=US
        expectedConstraints[2] = 1464662865008959075347130388737553683672515905673906344791000457739484483820;// Verified=true
        expectedConstraints[3] = 1464662865008959075347130388737553683672515905673906344791000457739484483820;// Empty

        // 4. Extra parameters for IssuerVerifier
        bytes32 ctx = bytes32("LetsVerify");
        string memory tokenURI = "ipfs://QmVXzY1QerAQ8y7QPMaPdPke82s5r6hyuYhYaMHfgNYZNg";
        string memory tokenName = "LetsVerify";
        string memory tokenSymbol = "LetV";

        // 5. Deploy the IssuerVerifier
        IssuerVerifier issuerVerifier = new IssuerVerifier(
            address(bbsVerifier), 
            ctx, 
            expectedConstraints,
            tokenURI,
            tokenName,
            tokenSymbol
        );

        console.log("BBSVerifier deployed at:", address(bbsVerifier));
        console.log("IssuerVerifier deployed at:", address(issuerVerifier));

        vm.stopBroadcast();
    }
}